name: muraloka
description: "Muraloka Apps for Kementrian Badan Pariwisata dan Ekonomi Kreatif
  Indonesia Upskilling Program Capstone Project"
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.9.0

dependencies:
  bloc: ^9.0.0
  cached_network_image: ^3.3.1
  cloud_firestore: ^6.0.2
  custom_flutter_painter: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.9.0
  equatable: ^2.0.7
  file_picker: ^8.1.4
  firebase_auth: ^6.1.0
  firebase_core: ^4.1.0
  firebase_core_web: ^3.1.0
  firebase_ui_auth: ^3.0.0
  flex_color_picker: ^3.6.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_launcher_icons: ^0.14.4
  flutter_phosphor_icons: ^0.0.1+6
  get_it: ^8.2.0
  go_router: ^16.2.1
  google_fonts: ^4.0.4
  open_file: ^3.5.10
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  pretty_qr_code: ^3.5.0
  qris: ^0.7.1
  share_plus: ^12.0.1
  shared_preferences: ^2.5.3
  skeletonizer: ^2.1.0+1
  sqflite: ^2.4.2
  webview_flutter: ^4.13.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

fonts:
  - family: SocialIcons
    fonts:
      - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf
assets:
  - assets/images/
  - assets/icons/
  - assets/images/logo_muraloka.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_muraloka.png"