// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPfEEqVsG8GeayUyncHH_GmXqFgQ_XP4w',
    appId: '1:444914900205:web:4b87384ec15a51af8880e4',
    messagingSenderId: '444914900205',
    projectId: 'muraloka-apps',
    authDomain: 'muraloka-apps.firebaseapp.com',
    storageBucket: 'muraloka-apps.firebasestorage.app',
    measurementId: 'G-JX9HJPNPN9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_DfYjzBsFr_-lCw7rexTqv-I4HPZ5w7c',
    appId: '1:444914900205:android:cbf98a01460ad3078880e4',
    messagingSenderId: '444914900205',
    projectId: 'muraloka-apps',
    storageBucket: 'muraloka-apps.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHOkKoDZMU0T05zA2JBIpnCD_hFJVcE44',
    appId: '1:444914900205:ios:1f6d78507273cd6d8880e4',
    messagingSenderId: '444914900205',
    projectId: 'muraloka-apps',
    storageBucket: 'muraloka-apps.firebasestorage.app',
    iosClientId: '444914900205-ki1b1l09is0hj11onb3i90h5vbm515k2.apps.googleusercontent.com',
    iosBundleId: 'com.example.muraloka',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHOkKoDZMU0T05zA2JBIpnCD_hFJVcE44',
    appId: '1:444914900205:ios:1f6d78507273cd6d8880e4',
    messagingSenderId: '444914900205',
    projectId: 'muraloka-apps',
    storageBucket: 'muraloka-apps.firebasestorage.app',
    iosClientId: '444914900205-ki1b1l09is0hj11onb3i90h5vbm515k2.apps.googleusercontent.com',
    iosBundleId: 'com.example.muraloka',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPfEEqVsG8GeayUyncHH_GmXqFgQ_XP4w',
    appId: '1:444914900205:web:4bcbe31f0e7cbb358880e4',
    messagingSenderId: '444914900205',
    projectId: 'muraloka-apps',
    authDomain: 'muraloka-apps.firebaseapp.com',
    storageBucket: 'muraloka-apps.firebasestorage.app',
    measurementId: 'G-Z475BR8ZN2',
  );
}
